# Generated by Django 4.2 on 2023-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=2024)),
                ('available', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=10)),
                ('image_one', models.ImageField(upload_to='./media/product/img/%y/%m/%d/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='./media/product/img/%y/%m/%d/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='./media/product/img/%y/%m/%d/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='./media/product/img/%y/%m/%d/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='./media/product/img/%y/%m/%d/')),
                ('color_one', models.CharField(max_length=50)),
                ('color_two', models.CharField(blank=True, max_length=50, null=True)),
                ('color_three', models.CharField(blank=True, max_length=50, null=True)),
                ('color_four', models.CharField(blank=True, max_length=50, null=True)),
                ('color_five', models.CharField(blank=True, max_length=50, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.company')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
