# Generated by Django 4.2 on 2023-05-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_color_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_five',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_four',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_two',
        ),
    ]
