# Generated by Django 4.2 on 2023-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shoping',
            field=models.BooleanField(default=False),
        ),
    ]
