# Generated by Django 4.2 on 2023-06-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_free_shoping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_one',
            new_name='active_image',
        ),
    ]
