# Generated by Django 4.2 on 2023-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
